[project]
name = "raindrop-mcp"
version = "0.1.0"
description = "Raindrop.io MCP server for Claude Desktop"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "httpx>=0.24.0",
    "python-dotenv>=1.0.0",
]
